### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by cve** [KnpLabs/KnpRadBundle#101]
Hi,
when I run this command:

```
composer.phar create-project -s dev --prefer-dist --dev knplabs/rad-edition my_project
```

from the http://rad.knplabs.com/#installation
it shows the error from attachment
![error](https://f.cloud.github.com/assets/594384/606772/14f918c2-cd33-11e2-876b-dcb0c3bdc9d5.png)

**Comment by docteurklein** [comment]
It may come from a problem with packagist / network error / github zipball problems. Have you tried to relaunch the same command ? 

PS: this issue would go preferably on https://github.com/KnpLabs/rad-edition/issues.

**Comment by peterjwest** [comment]
I've just had the same bug.

Sensio are now 'sensiolabs' on github.
The composer file needs to be changed to "sensiolabs/distribution-bundle": "2.2.*",
and presumably in the lock file too.

**Comment by docteurklein** [comment]
They indeed renamed the github account, but packagist still register the package as `sensio/*`.

So I think it's still a packagist freshness issue, that could be solved by retrying now packagist points to correct repo.

**Comment by docteurklein** [comment]
But I'm maybe wrong :) However, if I check https://github.com/symfony/symfony-standard/blob/master/composer.json#L18 and https://packagist.org/packages/sensio/distribution-bundle, it seems to be correct.

**Comment by peterjwest** [comment]
That's weird, I literally just installed symfony standard with no issues.

**Comment by peterjwest** [comment]
Does this project install vendors from the lock file, meaning the github references are wrong?

**Comment by docteurklein** [comment]
ha! the lock file contains bad refs, indeed! Thanks, I'll fix that on rad-edition repository.

**Comment by docteurklein** [comment]
pushed a fix in branch 2.3 of rad-edtion.

**Comment by docteurklein** [comment]
pushed to master too :)

**Comment by docteurklein** [comment]
so, @cve @peterjwest  can you tell me if its ok for you ? thanks!

**Comment by cve** [comment]
yes, it works :) thanks
