### ISSUE TITLE
Translatable fields are not persisted when updating entity with RadController shortcuts

### ISSUE THREAD

**Issue by sandymoreno** [KnpLabs/KnpRadBundle#111]
I'm using knp translatable behavior and when object is created, translatable fields are persisted normally, but when object is updated changes on translatable fields are ignored. Ex I have this code in updateAction:

```
...
  /*This controller extends RadController*/

   if ($form->isValid()) {

    $entity->translate('fr')->setName('Chaussures');
    $entity->translate('en')->setName('Shoes');

        $this->persist($entity, true);

        return $this->redirectToRoute('somewhere');

    }
...
```

If instead call RadController shortcuts methods I persist entity like this, works perfect.

```
$this->getDoctrine()->getManager()->persist($entity);
$this->getDoctrine()->getManager()->flush();
```

**Comment by docteurklein** [comment]
yes, that's the normal behavior of flushing only one entity.

If you look at the `persist()` method of BaseController, you'll notice that it calls `flush($entity);` (when passing true as 2nd argument) which results in **not** saving any other entity than the one passed as argument.

If you want to avoid this behavior, simply modify you code like so:

``` php

   if ($form->isValid()) {

    $entity->translate('fr')->setName('Chaussures');
    $entity->translate('en')->setName('Shoes');

        $this->persist($entity);
        $this->flush();

        return $this->redirectToRoute('somewhere');
    }

```

Notice that you do not pass `true` anymore to the persist method, which results in not calling `flush($entity);` internally.

**Comment by docteurklein** [comment]
But that's indeed potentially a problem, since it's not said that `persist($entity, true)` will flush **only** the passed entity. Either it should be documented, or we should flush the **whole** unitOfWork.

**Comment by docteurklein** [comment]
Here is the doc: https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/EntityManager.php#L382

**Comment by docteurklein** [comment]
mmmh, let me think. Maybe what I said is just wrong :) 

May it come from the fact you did not merged new translations ?
If you add new translations that did not exist precedently in persisted collection,
you will have to call `$entity->mergeNewTranslations();` in order to make them persistable.

**Comment by sandymoreno** [comment]
No, I'm just updating existing translations. But I tested with $entity->mergeNewTranslations(); and not work.

**Comment by docteurklein** [comment]
ok ,so have you tried to use:

```
$this->persist($object);
$this->flush(); 
```

?

**Comment by sandymoreno** [comment]
Thanks!
