### ISSUE TITLE
It should be easy to override a 3rd party service.

### ISSUE THREAD

**Issue by docteurklein** [KnpLabs/KnpRadBundle#116]
For the moment it's only possible either via compiler pass or config.yml (right ?)

I'm thinking of an ultimate extension point that would be loaded after all the others.

**Comment by gquemener** [comment]
Dude, enjoy your holliday!

And after that, could you provide some example of what you mean by overriding 3rd party service, please?

**Comment by docteurklein** [comment]
héhé I am, thanks partly to you :)

I wanted to provide a more easy way to override services defined in another DI exension than yours.
For the moment, the only way is: http://symfony.com/doc/current/cookbook/bundles/override.html#services-configuration
and compiler passes.

We could add some stuff that permits to override any service with the same id, but using a yml file for example.

Example: framework bundle declares a `translator` service. 
How to override this service simply ? Answer: there is no "simple" way.

What could be cool is to add a `final` directory (or `after`, like in vim :) ) that is loaded **after** all others bundles and that permits to define service that could possibly override predefined ones.

Result would be:

``` yaml

# src/App/Resources/config/final/services.yml

services:
    translator:
        class: App\Translator


```

Apparently and IMHO `config.yml` already does that, but it could be cool to have a more structured way than to put everything in a huge config.yml file. (even if you could use `imports` statement).

Thougts?

**Comment by docteurklein** [comment]
Of course, all of this should be only available for an **app**, not from a bundle point of view.
A bundle should not be aware of services defined by others.

**Comment by docteurklein** [comment]
see what I mean @gquemener ?

**Comment by gquemener** [comment]
Well I think I remember overriding a service by redefining one with the same id in my bundle.
Wouldn't it ba a "simple" way?

**Comment by docteurklein** [comment]
nope, IMHO containers are isolated per bundle.

**Comment by docteurklein** [comment]
gosh, you're right.

**Comment by docteurklein** [comment]
order of bundle registration matters though.

**Comment by docteurklein** [comment]
sooo, is it still useful, when we are sure to register `App\App` bundle **after** all other bundles ?

**Comment by gquemener** [comment]
Well your solution would allow overriding services, no matter of the registration order.
But in most case, App bundle will be registered last (as in the rad edition) and thus allow to override any service by using the same id.

**Comment by gquemener** [comment]
So this nice idea might not be that needed...

**Comment by docteurklein** [comment]
yep indeed :)
