### ISSUE TITLE
[ResourceResolver] It should be more flexible

### ISSUE THREAD

**Issue by docteurklein** [KnpLabs/KnpRadBundle#119]
We should have a more convenient way to convert parameters to objects.

**Comment by cursedcoder** [comment]
You are saying it like we have some way to do it, but atm there is no such feature in rad bundle :)

**Comment by docteurklein** [comment]
yes there is :) http://rad.knplabs.com/#resource-resolver and https://github.com/KnpLabs/KnpRadBundle/wiki/Routing#complete-example

**Comment by docteurklein** [comment]
closed by #120
