### ISSUE TITLE
Security/sessions error in Max OS X Installation

### ISSUE THREAD

**Issue by ArlingtonHouse** [KnpLabs/KnpRadBundle#12]
Installing this great new bundle on Mac Lion with MAMP, getting this error when trying to view a page:

"ErrorException: Catchable Fatal Error: Object of class __PHP_Incomplete_Class could not be converted to string in /Applications/MAMP/htdocs/{PROJECT}/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php line 70"

I can probably solve it with a php.ini setting change, but since I'm using a very common dev environment I wanted to post the issue.  Thanks!

**Comment by everzet** [comment]
Hmm. Very strange. I'm on Mac Lion too, but without MAMP though :-/ Have you tried to clean the cache?

``` bash
rm -rf cache/*
```

**Comment by ArlingtonHouse** [comment]
I tried clearing cache, and that didn't work, but I also just restarted Chrome and now it is working great.  Thanks!
