### ISSUE TITLE
It should be easy to create a level4 RESTful API

### ISSUE THREAD

**Issue by docteurklein** [KnpLabs/KnpRadBundle#125]

**Comment by docteurklein** [comment]
by integrating zf-hal for example ?

**Comment by Djeg** [comment]
Ho nice Hal ^^. It's a good idea but i think an external bundle should be more scalable for Hal. No ? Anyway it seems that hal formater always exists. So, why not.

**Comment by docteurklein** [comment]
yeah, I'm crazy. I don't know why I put this in radBundle. It should definitly be an indepedant piece of software :)

What I meant is to have an integrated solution in rad-edition (I should move the ticket to rad-edition repo).

**Comment by docteurklein** [comment]
closed in favor of Knplabs/rad-edition#17
