### ISSUE TITLE
describe features using behat

### ISSUE THREAD

**Issue by docteurklein** [KnpLabs/KnpRadBundle#127]
this would kill two birds with one stone:
- have an explicit, self-explanative list of features
- test the bundle in black box mode

**Comment by inoryy** [comment]
How to initialize Behat on a bundle though? Where will we get stuff like `AppKernel.php` and `app_test.php`?

**Comment by docteurklein** [comment]
kindof this way: http://www.zalas.eu/run-behat-scenarios-and-functional-tests-from-symfony-bundle-in-isolation-of-project

**Comment by docteurklein** [comment]
We make a default appkernel, register RadBundle, and App < AppBundle, instanciate and boot the kernel,
and make requests on it.

**Comment by docteurklein** [comment]
here is an example of how to describe phpspec features: https://github.com/docteurklein/Symfony2Extension/blob/01363b047d9242e0983adf5ace677d364cc2eee5/features/initialize_default_collaborators.feature

and the context: https://github.com/docteurklein/Symfony2Extension/blob/01363b047d9242e0983adf5ace677d364cc2eee5/features/bootstrap/PhpSpecContext.php
