### ISSUE TITLE
ServiceCircularReferenceException

### ISSUE THREAD

**Issue by mbontemps** [KnpLabs/KnpRadBundle#163]
I regularly see these errors in my logs with the latest rad-bundle (5fa07b06feec048e208c2a1b8c32f479452a9483):

```
Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException' with message 'Circular reference detected for service "knp_rad.domain_event.dispatcher.delayed", path: "knp_rad.domain_event.dispatcher.delayed -> doctrine.dbal.default_connection.event_manager".' in /home/my_project/app/bootstrap.php.cache:2010
Stack trace:
#0 /home/my_project/app/cache/prod/appProdDebugProjectContainer.php(5037): Symfony\Component\DependencyInjection\Container->get('knp_rad.domain_...')
#1 /home/my_project/app/bootstrap.php.cache(2033): appProdDebugProjectContainer->getDoctrine_Dbal_DefaultConnection_EventManagerService()
#2 /home/my_project/app/cache/prod/appProdDebugProjectContainer.php(2728): Symfony\Component\DependencyInjection\Container->get('doctrine.dbal.d...')
#3 /home/my_project/app/bootstrap.php.cache(2033): app in /home/my_project/app/bootstrap.php.cache on line 2010
```

I haven't yet managed to see where this is coming from… any idea?

**Comment by Nek-** [comment]
Probably #144 relatead.

**Comment by docteurklein** [comment]
no clue exactly, but I don't think it's #144 related since it has been fixed.

Can you paste or link to something that I can reproduce ?

**Comment by mbontemps** [comment]
Hard to reproduce, but I finally got a clue of where this is happening.

It's when used together with the https://github.com/nelmio/NelmioCorsBundle

Every `OPTIONS` request (but not the first one) leads to this error…

**Comment by mbontemps** [comment]
I've reproduced the issue in a minimal environment.

https://github.com/mbontemps/bug-rad-cors

There is a script in here which does the `OPTIONS` request - and fails:

https://travis-ci.org/mbontemps/bug-rad-cors

**Comment by mbontemps** [comment]
And… more info: my tests pass with versions prior to 2a8fa14dd8db517b3d195542a652d5b51ae92fcc, so this comes from THIS commit!

Hope that helps!

**Comment by docteurklein** [comment]
thanks a lot!

**Comment by mbontemps** [comment]
I can confirm that this works for me, thanks! :thumbsup:

**Comment by docteurklein** [comment]
thanks for the feedback :)
