### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by neclimdul** [KnpLabs/KnpRadBundle#17]
There doesn't seem to be any mention of licensing in the repository or anywhere I could find. Having something would be reassuring since public domain can sometimes be a bit... sticky.

**Comment by everzet** [comment]
Yeah, we'll add license tomorrow. But i'm 99.999999% sure we'll choose MIT - same license we use for every our OpenSource project. So, don't worry.

**Comment by gquemener** [comment]
done 85745d1662976f2ef4e6a8f30ea00b2b26f98cae
