### ISSUE TITLE
We need a new stable release

### ISSUE THREAD

**Issue by akovalyov** [KnpLabs/KnpRadBundle#177]
@docteurklein the latest release is 2.3.2(actually, GitHub shows v2.3.1 as latest) which is incompatible with stable symfony 2.5.0 
`Knp\RadBundle\Controller\Controller::createAccessDeniedException->createAccessDeniedException()` has another access level than https://github.com/symfony/symfony/commit/183d0ec302d3eece21a8f8766c899641132cedeb

**Comment by docteurklein** [comment]
ho, thanks for pointing this out!

I'll try to do that ASAP, but I haven't much time right now.

**Comment by docteurklein** [comment]
I just removed this method, since it as already defined in the base class.

Can you tell me if it fixes the probkem for you ?
If so, I'll tag a new release.

**Comment by akovalyov** [comment]
@docteurklein I would be happy to say that it fixes the problem

``` diff
diff --git a/composer.json b/composer.json
-        "knplabs/rad-bundle": "~2.3@dev",
+        "knplabs/rad-bundle": "dev-develop as ~2.3@dev",
```

I am just using clean RAD edition, cloned this night
When I open the homepage - I get

```
ServiceCircularReferenceException: Circular reference detected for service 
"knp_rad.domain_event.dispatcher.delayed", path: "knp_rad.domain_event.dispatcher.delayed -> 
doctrine.dbal.default_connection.event_manager".
```

**Comment by docteurklein** [comment]
this is another issue, #163

**Comment by akovalyov** [comment]
@docteurklein so we can not have the release at the moment since c9f7b0b5eb0654e09720b2651902365fa7b2d8b3(which is parent commit for https://github.com/KnpLabs/KnpRadBundle/issues/163#issuecomment-38379197) does contain the same `Knp\RadBundle\Controller\Controller::createAccessDeniedException->createAccessDeniedException()`
:(

**Comment by docteurklein** [comment]
I just pushed a new tag: 2.5.0

**Comment by docteurklein** [comment]
BTW, we need to be more semver compliant, because currently: ![noidea](https://mondaybynoon.com/wp-content/uploads/xVyoSl.jpg)

**Comment by docteurklein** [comment]
closing for now. thanks!
