### ISSUE TITLE
Translations not loaded in src/KnpRad/Resources/translations

### ISSUE THREAD

**Issue by nmariani** [KnpLabs/KnpRadBundle#18]
I wasted my time and crashed my head against the wall today.
I was trying to translate my app by putting translations into src/MyApplication/Resources/translations/messages.fr.yml.
But I still had Shakespeare's language instead of Moliere until I moved translation files into /app/Resources/translations.

What's wrong ? Have you got the same issue ? Looks like a bug for me or maybe we should update the documentation.

**Comment by juliensnz** [comment]
Same problem here. 

But I don't resolved it just by adding my translation file in app/Resources/translations.... I'm desperate !
