### ISSUE TITLE
rename jquery-ujs.

### ISSUE THREAD

**Issue by ghost** [KnpLabs/KnpRadBundle#186]
This would be very hard to search for  as it is the same name as the thing included in rails.  It'd also lead to people expecting the exact same functionality as rails jquery-ujs .

I don't have a name suggestion otherwise i would have submitted a PR.

on a similiar note.. is there any reason you don't just use a forked version of rails jquery-ujs?

**Comment by ghost** [comment]
for any passersby not familiar with it

https://github.com/rails/jquery-ujs/blob/master/src/rails.js

**Comment by docteurklein** [comment]
You're right, we should rename it to something like "link-attributes.js" or something. (at least it would follow the php naming, even though it may not be ideal).

**Comment by ghost** [comment]
so is there any reason not to use a forked version jquery-ujs ? it doesn't seem like it'd take much modification?

**Comment by docteurklein** [comment]
I think we studied the case at the time, and found out that rail's ujs allows only one csrf per page,
so you can't handle different `intentions` for different links.

**Comment by ghost** [comment]
ah good point.  still some other neat stuff that might be worth copying tho.

**Comment by ghost** [comment]
oh. i should thank you folks for writing this. saved me from having to write it myself or try to debug untested code from stackoverflow!. It works like a charm :)
