### ISSUE TITLE
twitter bootstrap 3?

### ISSUE THREAD

**Issue by chrisyue** [KnpLabs/KnpRadBundle#188]
thanks for the awesome project !!

can twitter bootstrap be upgrade to 3 ?

**Comment by docteurklein** [comment]
hello :) thanks for opening the issue. I see no problem in using v3, if you wich to propse a PR, It would be awesome!

But on the long term, I don't think it's the role of this bundle to handle view specific things.
Anyway, you can already use v3 with this bundle in cunjuction: just extend your custom base layout, that includes bsv3.

**Comment by chrisyue** [comment]
@docteurklein I think you're right, And I found MopabootstrapBundle is more suitable. :+1:

**Comment by docteurklein** [comment]
right, mopa bootstrap is surely the way to go
