### ISSUE TITLE
fatal error during install

### ISSUE THREAD

**Issue by brikou** [KnpLabs/KnpRadBundle#21]
I wanted to test this promising bundle, bunt during composer install, I get... ;(

```

[ErrorException]
  symlink(): Operation not supported

```

**Comment by l3l0** [comment]
@brikou I think that it can be some composer issue. You should provide us some additonal informations... like version of composer, which operating system did you use... you know stuff like that...

**Comment by brikou** [comment]
@l3l0 sorry about that ... I've open an issue with composer ;)
