### ISSUE TITLE
Symfony 2.7 support

### ISSUE THREAD

**Issue by vkalmuk** [KnpLabs/KnpRadBundle#210]
Are there any plans to support symfony 2.7, 2.8, 3.x ... ?

**Comment by keltanas** [comment]
+1
Without this have to rewrite my project, removing all references RadBundle. Sadness.

**Comment by docteurklein** [comment]
I have no plan to verify what is needed to support newer versions, but if someone is ready to make a PR, don't hesitate :)

**Comment by docteurklein** [comment]
BTW, except maybe some deprecations I didn't see, I see nothing that blocks you from using 2.8 yet.

If you are aware of any problem with newer versions, please report.

**Comment by einenlum** [comment]
:+1: @docteurklein.
@vkalmuk & @keltanas : What is stopping you using newer versions?

**Comment by keltanas** [comment]
@Einenlum well, e.g. composer.json 
https://github.com/KnpLabs/KnpRadBundle/blob/v2.6.3/composer.json

```
    "require": {
        "php":                      ">=5.4",
        "symfony/symfony":          "~2.4,<2.7",
        "nelmio/alice":             "~1.5",
        "fzaninotto/faker":         "~1.2"
    },
```

However, I have refactored a project to ExtraBundle

**Comment by einenlum** [comment]
@keltanas It seems it was fixed in version 2.7.0 https://github.com/KnpLabs/KnpRadBundle/releases/tag/2.7.0

**Comment by keltanas** [comment]
@Einenlum Unfortunately not seen this tag earlier

**Comment by einenlum** [comment]
I close the issue. We will reopen it if there still is a problem.
