### ISSUE TITLE
[Bug] rad:generate:controller cause error if multilevel sub namespace was passed

### ISSUE THREAD

**Issue by yberkholz** [KnpLabs/KnpRadBundle#23]
**example**
console rad:generate:controller Level1/Level2/Level3:index

**expected controller namespace**
${AppBundleNS}\Level1\Level2\Level3;

**generated controller namespace**
${AppBundleNS}\Level1\Level2/Level3;

causes: _"Parse error: syntax error, unexpected '/', expecting T_NS_SEPARATOR or ';' or '{' in...."_

**Solution**
Replacement for GenerateControllerCommand:execute in L44

``` php
$subns     = str_replace('/', '\\', dirname(str_replace('\\', '/', $class)));
```

**Comment by docteurklein** [comment]
can you make a PR for that please ?

**Comment by yberkholz** [comment]
Done

**Comment by docteurklein** [comment]
Many thanks!
