### ISSUE TITLE
How to register bundles that require constructor arguments?

### ISSUE THREAD

**Issue by ronnylt** [KnpLabs/KnpRadBundle#26]
For example, to register the  JMS Serializer Bundle is required to do something like this: 

``` php
bundles = array(
    // ...
    new JMS\SerializerBundle\JMSSerializerBundle($this),
    // ...
);

```

In these cases, how to register bundles in kernel.yml ? 

Thanks.

**Comment by pjedrzejewski** [comment]
The **KnpRadBundle** automatically passes Kernel as argument to every bundle registered.

**Comment by ronnylt** [comment]
Perfect, thank you.
