### ISSUE TITLE
Providing a javascript for unsupported method call

### ISSUE THREAD

**Issue by gquemener** [KnpLabs/KnpRadBundle#38]
What about providing a javascript loaded in the rad base template that will handle DELETE, PUT, PATCH, ... method that can't be handled in html5 directly?
Something like :

``` javascript
    jQuery('body').on('click', 'a.delete', function (event) {
        event.preventDefault();

        if (confirm(jQuery(event.target).data('confirm') || 'Are you sure?')) {
            var form    = document.createElement('form');
            var input   = document.createElement('input');

            form.method = 'POST';
            form.action = event.currentTarget.href;

            input.type  = 'hidden';
            input.name  = '_method';
            input.value = 'DELETE';

            form.appendChild(input);
            document.body.appendChild(form);

            form.submit();
        }
    });
```

I'm getting tired of copy/pasting it to every project I work on :tongue:

**Comment by ruudk** [comment]
:+1: 

Maybe it would be better if you would follow the Rails way to do this instead of a.delete:

`<a href="/post"  data-method="post">Post</a>`

**Comment by gquemener** [comment]
Yeah I was thinking of that.

``` html
<a href="/crazy-action" data-method="delete" data-confirm="You sure?" />
<a href="/crazy-action" data-method="patch" />
<a href="/crazy-action" data-method="put" />
<a href="/crazy-action" data-method="post" />

<form action="/crazy-action" method="delete" data-confirm="You sure?" />
<form action="/crazy-action" method="put" />
<form action="/crazy-action" method="patch" />
```

**Comment by gquemener** [comment]
Why not simply use rails jquery-ujs script? https://github.com/rails/jquery-ujs/blob/master/src/rails.js

I mean, it's well-written, well-tested, already-used in a famous framework, under MIT licence, ...
And it already handles ajax submition, confirmation, form, anchor and csrf protection!

EDIT:
Oh and it handles method wrapping the same way: _method
