### ISSUE TITLE
Installing does not work (or i do it wrong :))

### ISSUE THREAD

**Issue by roderik** [KnpLabs/KnpRadBundle#4]
I'm trying to follow the installation instructions but it does not install, it only shows question marks.

Lion 10.7.3
PHP (built in) and the Liip one (http://php-osx.liip.ch/)

```
$ php composer.phar install
?? ???
```

**Comment by Palleas** [comment]
It's a PHAR issue, not RadBundle IMHO. It kinda sucks sometimes :)
Did you take a look at this : http://silex.sensiolabs.org/doc/usage.html#pitfalls ?

I that soesn't work, try using composer from the sources.

Hope it helps!

**Comment by pilot** [comment]
try to different ways to install composer https://github.com/composer/composer

**Comment by roderik** [comment]
adding 

```
detect_unicode = Off
phar.readonly = Off
phar.require_hash = Off
suhosin.executor.include.whitelist = phar
```

fixed it, thx
