### ISSUE TITLE
Unable to use subdirectories with routing

### ISSUE THREAD

**Issue by oste** [KnpLabs/KnpRadBundle#53]
I am trying to break my controllers up into two folders, "frontend" and "admin". So I added the following routes to my routing.yml

```
App:Frontend:Home:index: /
App:Admin:Post:index: /admin/posts/
```

When I visit the home page of the site I get the following error:

`Unable to find controller "App:Frontend" - class "App\Controller\FrontendController" does not exist.`

Is this something that should or will be supported by the KnpRadBundle?

**Comment by docteurklein** [comment]
It's not supported yet but it should :) This routing loader still needs some love.

**Comment by rfkm** [comment]
I tried the following code.

```
App:Frontend\Post:
    prefix: /post
App:Admin\Post: ~
```

then I got the following result

```
app_frontend_post_index           GET      /post/
app_frontend_post_new             GET      /post/new
app_frontend_post_create          POST     /post/
app_frontend_post_show            GET      /post/{id}
app_frontend_post_edit            GET      /post/{id}/edit
app_frontend_post_update          PUT      /post/{id}
app_frontend_post_delete          DELETE   /post/{id}
app_admin_post_index              GET      /admin/post/
app_admin_post_new                GET      /admin/post/new
app_admin_post_create             POST     /admin/post/
app_admin_post_show               GET      /admin/post/{id}
app_admin_post_edit               GET      /admin/post/{id}/edit
app_admin_post_update             PUT      /admin/post/{id}
app_admin_post_delete             DELETE   /admin/post/{id}
```

It seems to work. Controller mapping is also ok. Is there any problem?

**Comment by oste** [comment]
I can confirm that this works.

`App:Frontend\Home:index: /`

and it uses the Resources/views/Frontend/Home/index.html view file.

**Comment by docteurklein** [comment]
yes it works, sorry for confusion.
