### ISSUE TITLE
[RFC][Routing] Controllers in sub folders

### ISSUE THREAD

**Issue by leevigraham** [KnpLabs/KnpRadBundle#59]
I like to keep my Controllers namespaced depending on their purpose. For example:
- App/Controllers/Api/ProjectsController
- App/Controllers/Admin/ProjectsController
- App/Controllers/App/ProjectsController

Is this currently possible in KnpRadBundle if not would a pull request be in scope of the project.

**Comment by docteurklein** [comment]
yes it's possible: just use

```
App:Api\Projects: ~

```

in your routing.

duplicate of #53
