### ISSUE TITLE
Security voter service registration failing

### ISSUE THREAD

**Issue by oste** [KnpLabs/KnpRadBundle#61]
I have a Voter located at `App->Security->JobVoter.php` that looks something like this

``` php
namespace App\Security;

use Symfony\Component\Security\Core\Authorization\Voter\VoterInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use App\Entity\Job;

class JobVoter implements VoterInterface, ContainerAwareInterface
{
    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }

    public function supportsAttribute($attribute)
    {
        return in_array($attribute, [
            'OWNER'
        ]);
    }

    public function supportsClass($object)
    {
        return $object instanceof Job;
    }

    public function vote(TokenInterface $token, $object, array $attributes)
    {
        if (null === $object || !$this->supportsClass($object)) {
            return VoterInterface::ACCESS_ABSTAIN;
        }

        foreach ($attributes as $attribute) {
            if ($this->supportsAttribute($attribute)) {
                switch ($attribute) {
                    case 'OWNER':
                    if ($token->getUser() !== $object->getCreatedBy()) {
                        return self::ACCESS_DENIED;
                    }
                    break;
                }
            }
        }

        return self::ACCESS_GRANTED;
    }
}
```

This is giving me the following error:

```
FatalErrorException: Error: Cannot use object of type Symfony\Component\DependencyInjection\Reference as array in ../vendor/knplabs/rad-bundle/Knp/RadBundle/DependencyInjection/DefinitionManipulator.php line 12
```

**Comment by gquemener** [comment]
I was able to autoregister the following voter : 

``` php
<?php

namespace App\Security;

use Symfony\Component\Security\Core\Authorization\Voter\VoterInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;

class FooVoter implements VoterInterface
{
    public function supportsAttribute($attribute)
    {
        return true;
    }

    public function supportsClass($class)
    {
        return true;
    }

    public function vote(TokenInterface $token, $object, array $attributes)
    {
        return self::ACCESS_GRANTED;
    }
}
```

Can you try with it and tell me if it goes wrong, please?
Which version of the rad bundle are you using? Should be `2.*`

**Comment by oste** [comment]
Hi Gildas,

I replaced my code with your code and I am still getting the same results. I am using version 2.2 of the rad bundle.

**Comment by gquemener** [comment]
Weird...

While I'm investigating, can you post the full stack trace please?

**Comment by oste** [comment]
Sorry Gildas, that is all of the information that is being put on the screen :(

**Comment by gquemener** [comment]
What happens when you run `php app/console container:debug` ?
(try to remove your cache first: `rm -rf app/cache/*`)

**Comment by oste** [comment]
Removing the cache does not solve the issue.

When I run container:debug I get the same error as mentioned above.

On Tue, Mar 12, 2013 at 11:11 AM, Gildas Quéméner
notifications@github.comwrote:

> What happens when you run php app/console container:debug ?
> (try to remove your cache first: rm -rf app/cache/*)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/KnpLabs/KnpRadBundle/issues/61#issuecomment-14780699
> .

## 

Regards,
Mike

**Comment by gquemener** [comment]
Ok could you debug the file https://github.com/KnpLabs/KnpRadBundle/blob/develop/DependencyInjection/DefinitionManipulator.php#L11 and tell me what is the value of `$values` on line 11? shoud be an `array`

**Comment by oste** [comment]
`$values` is Symfony\Component\DependencyInjection\Reference

**Comment by gquemener** [comment]
OK, can you post your composer.json ?

**Comment by gquemener** [comment]
Or if I may have an access to your code, that would be helpful :)

**Comment by oste** [comment]
Sure, can I contact you at the email on your github page https://github.com/gquemener?

**Comment by gquemener** [comment]
It might be interesting to rename `JobVoter` to `JobVoterBack` and check the `security.access.decision_manager` service in the container (`app/cache/dev/appDevDebugProjectContainer.php`).

It should look like (argument 1 is an array):

``` php
    protected function getSecurity_Access_DecisionManagerService()
    {
        return $this->services['security.access.decision_manager'] = new \Symfony\Component\Security\Core\Authorization\AccessDecisionManager(array(0 => new \Symfony\Component\Security\Core\Authorization\Voter\RoleHierarchyVoter(new \Symfony\Component\Security\Core\Role\RoleHierarchy(array('ROLE_ADMIN' => array(0 => 'ROLE_USER'), 'ROLE_SUPER_ADMIN' => array(0 => 'ROLE_USER', 1 => 'ROLE_ADMIN', 2 => 'ROLE_ALLOWED_TO_SWITCH')))), 1 => new \Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter($this->get('security.authentication.trust_resolver')), 2 => $this->get('app.security.foo_voter')), 'affirmative', false, true);
    }
```

**Comment by gquemener** [comment]
Sure @oste, no problem

**Comment by oste** [comment]
email sent.

**Comment by gquemener** [comment]
The problem is that our compiler pass that registered the security voters is incompatible with the `JMSSecurityExtraBundle`.
Sooo, for this one we've made a workaround (https://github.com/KnpLabs/KnpRadBundle/pull/62).

**Comment by docteurklein** [comment]
It's more the JMS SecurityExtra bundle that changes the default behavior.
 Another possibility is to move the JMS's compiler pass to be AFTER optimisation.

Any thoughts @schmittjoh ?

**Comment by schmittjoh** [comment]
Hm yeah, inter-bundle integration is tricky; it's certainly possible to move the compiler pass, but I don't know if/what this will break then. 

Could you register your compiler pass before the one from security extra?

**Comment by docteurklein** [comment]
@schmittjoh We tried that without success. We found a workaround: see #64

**Comment by docteurklein** [comment]
@oste please use the latest KnpRandBundle and configure your application using:

```
knp_rad:
    security:
        decision_manager: security.access.decision_manager.delegate

```
