### ISSUE TITLE
Add documentation on flashes tag

### ISSUE THREAD

**Issue by gquemener** [KnpLabs/KnpRadBundle#69]
Dear @Herzult,

I hope everything is going well for you in the country of Andouillette.
Would it be possible that you add some usage documentation on the flashes tag?
At least, so we can update the base tb layout that still uses app.session.flashes (which is baaaad).

Sincerly yours,

GildasQ.

**Comment by docteurklein** [comment]
lol.

**Comment by docteurklein** [comment]
talking about flashes, I just encountered a problem where flashes block cannot access context variables.
