### ISSUE TITLE
wrong imagine bundle used

### ISSUE THREAD

**Issue by stof** [KnpLabs/KnpRadBundle#7]
Your skeleton for the Imagine config uses an old bundle (a fork of the first bundle created by @avalanche123 and deleted long ago). This bundle is incompatible with both Symfony (it is written for PR10 or something like that) and Imagine

you should use https://github.com/avalanche123/AvalancheImagineBundle (official basic integration) or https://github.com/liip/LiipImagineBundle (most advanced features as @avalanche123 wanted to keep his own bundle very simple). And the best solution would be to provide the skeleton for both of course :)

**Comment by pilot** [comment]
thanks, I'll update it
