### ISSUE TITLE
Why was the assetic pipeline removed?

### ISSUE THREAD

**Issue by pvolok** [KnpLabs/KnpRadBundle#71]
I didn't use it, but wanted to try it now. And was surprised that it was removed in 2.0. What are the reasons behind that?

**Comment by docteurklein** [comment]
The reason is it should be included in assetic directly.

**Comment by docteurklein** [comment]
The legacy code is still available, and it should not be that hard to include manually:

https://github.com/KnpLabs/KnpRadBundle/blob/d595b720c715878ddf46341718aa45640d9f440e/Resources/config/assetic_pipeline.xml

https://github.com/KnpLabs/KnpRadBundle/blob/d595b720c715878ddf46341718aa45640d9f440e/DependencyInjection/KnpRadExtension.php#L60

https://github.com/KnpLabs/KnpRadBundle/blob/d595b720c715878ddf46341718aa45640d9f440e/DependencyInjection/Compiler/AsseticPipelinePass.php

https://github.com/KnpLabs/KnpRadBundle/blob/d595b720c715878ddf46341718aa45640d9f440e/DependencyInjection/Compiler/ApplicationTemplateResourcesPass.php

**Comment by pvolok** [comment]
Thank you. I was curious because it would make more sense if it was first included in assetic and after that removed from KnpRadBundle :-)

**Comment by docteurklein** [comment]
apparently, it asks for a lot of work to be included into assetic.

**Comment by docteurklein** [comment]
And we prefer radBundle V2 to focus on one and only thing: no asset stuff, just MVC.
