### ISSUE TITLE
Create Validator in Controller. 

### ISSUE THREAD

**Issue by ghost** [KnpLabs/KnpRadBundle#73]
Hi,

I have problem with validation.

In my controller:

```
$User = new User();
$User->setFirstName('Martin');
$User->setLastName('Grochulski');

$validator = $this->container->get('validator');
$errors = $validator->validate($User);
var_dump($errors);
```

I have create the validation with annotation in my User Entity,

When I do that, symfony return:

FatalErrorException: Error: Cannot instantiate abstract class Knp\RadBundle\Doctrine\EntityRepository in /vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php line 689

**Comment by ghost** [comment]
The problem is when I use: @UniqueEntity("email") in Entity

**Comment by docteurklein** [comment]
which version are you using ? Since 42bc82d , the default entity repository is concrete. You should update knpradbundle, OR modify the default repository class: 

https://github.com/KnpLabs/rad-edition/blob/master/app/config/config.yml#L57

**Comment by gquemener** [comment]
Yep we should tag a new minor version (maybe wait for https://github.com/KnpLabs/KnpRadBundle/pull/72 to merged).
In the meantime, you can use `dev-develop@dev` in composer.

**Comment by ghost** [comment]
Hi,

@gquemener thx, now it's work ;]

**Comment by gquemener** [comment]
@marcingrochulski You may now use fresh tag [v2.3](https://github.com/KnpLabs/KnpRadBundle/tree/v2.3)
