### ISSUE TITLE
v2.3 tag creation

### ISSUE THREAD

**Issue by gquemener** [KnpLabs/KnpRadBundle#74]
Last tag (v2.2) is a month and a half old. Let's make another one to add this 27 new awesome commits! https://github.com/KnpLabs/KnpRadBundle/compare/v2.2...develop

ping @Herzult @docteurklein

**Comment by docteurklein** [comment]
agree; it contains fixes that should be available in stable version too.

**Comment by gquemener** [comment]
up

**Comment by docteurklein** [comment]
done! https://github.com/KnpLabs/KnpRadBundle/tree/v2.3

**Comment by gquemener** [comment]
![Party Hard](http://stfu.lelombrik.net/767.gif)

**Comment by docteurklein** [comment]
le GIIIIF

**Comment by docteurklein** [comment]
oooooh meeerde

**Comment by PedroTroller** [comment]
![tumblr_lwq0jjpeg01r8lfixo1_500](https://f.cloud.github.com/assets/1766827/401244/d810305e-a8d3-11e2-922e-2a1af42fc431.gif)

**Comment by gquemener** [comment]
![messy](http://stfu.lelombrik.net/835.gif)

**Comment by docteurklein** [comment]
ouais vas Y!

**Comment by PedroTroller** [comment]
![what-is-love-570898416](https://f.cloud.github.com/assets/1766827/401255/6db5e14e-a8d4-11e2-9f8e-43ec2c2de0b9.gif)

**Comment by docteurklein** [comment]
![party](http://25.media.tumblr.com/tumblr_mcbocfncWK1qkf3ufo1_500.gif)

**Comment by PedroTroller** [comment]
![party](http://24.media.tumblr.com/tumblr_m5q9htO3Qo1rpoka3o1_400.gif)

**Comment by PedroTroller** [comment]
![PARTY_6f9750_2098765](https://f.cloud.github.com/assets/1766827/401279/f7c0de16-a8d4-11e2-84ab-e8c2847c72ea.gif)

**Comment by gquemener** [comment]
![Party hard](http://stfu.lelombrik.net/696.gif)

**Comment by PedroTroller** [comment]
![carlton-dance_o_gifsoup-com 1 ](https://f.cloud.github.com/assets/1766827/401289/76b9186e-a8d5-11e2-9c3b-d77d141dd67f.gif)

**Comment by Herzult** [comment]
![](http://img.pandawhale.com/40235-Spent-the-weekend-with-85yo-gr-NQyU.gif)

**Comment by PedroTroller** [comment]
![tumblr_ly3feuNBRL1qh8azno1_r1_500](https://f.cloud.github.com/assets/1766827/401674/ae8a208a-a8e4-11e2-8f53-6c8101b96613.gif)

**Comment by cursedcoder** [comment]
![asdasdasd](http://friends.kz/uploads/17042013/gifs_06.gif)

**Comment by cursedcoder** [comment]
![sad](http://friends.kz/uploads/17042013/gifs_12.gif)

**Comment by ghost** [comment]
![party-hard_o_926441](https://f.cloud.github.com/assets/1177637/405022/08a36414-a9a8-11e2-8b44-d3706fa90ab7.gif)
