### ISSUE TITLE
csrf protected links as external bundle

### ISSUE THREAD

**Issue by jakoss** [KnpLabs/KnpRadBundle#80]
Hi
Is there any possibility to find/make this functionality https://github.com/KnpLabs/KnpRadBundle/wiki/csrf-protected-links as external bundle or sth? I got big project and i can't afford to convert it all to KnpRadBundle (sadly i found it too late :() and i'm looking for csrf protection for links. Your solution is the best, but still - it's attached to Rad Bundle. Can anybody help me with that?

**Comment by gquemener** [comment]
I don't know if anything is planned about extracting some parts of the rad bundle to external bundles, but in the meantime you could just use this listener into your application https://github.com/KnpLabs/KnpRadBundle/blob/develop/EventListener/CsrfListener.php

**Comment by gquemener** [comment]
And this twig ext to generate token https://github.com/KnpLabs/KnpRadBundle/blob/develop/Twig/LinkAttributesExtension.php

**Comment by jakoss** [comment]
Thx, you are great! I'll close issue when i'll make it work :)

**Comment by gquemener** [comment]
ok, don't hesitate to ask for help if anything goes wrong :wink:

**Comment by docteurklein** [comment]
yes. Just don't register the knprad bundle instance, and copy the service definitions for these 2 classes. And you're ready to go :)

**Comment by jakoss** [comment]
Works great, thanks you all for helping me out! :+1:
