### ISSUE TITLE
Command generate:bundle does not exist

### ISSUE THREAD

**Issue by zender** [KnpLabs/KnpRadBundle#81]
Hi guys,
when trying to generate a bundle 
"php app/console generate:bundle --namespace=MyNS\MyBundle --format=xml"
I get the following error:  
Command "generate:bundle" is not defined. 

Is that command supported in KnpRadBundle?

**Comment by gquemener** [comment]
KnpRadBundle v2.\* is not about code generation but about conventions. So you won't find any code generator there.
I suggest you take a look at https://github.com/sensio/SensioGeneratorBundle (or possibly at KnpRadBundle v1-deprecated on the master branch of the current repo).

**Comment by docteurklein** [comment]
Yes, this command comes from SensioGeneratorBundle, the knprad v1 does not have it neither.
