### ISSUE TITLE
automatically disable features that have missing services

### ISSUE THREAD

**Issue by lsmith77** [KnpLabs/KnpRadBundle#93]

**Comment by gquemener** [comment]
Could you be more specific please?

**Comment by lsmith77** [comment]
sorry .. was in a rush back then.

i fixed the issue by config:

```
knp_rad:
    listener:
        orm_user: false
```

in the RAD spirit it might however make sense to automatically discover that the relevant services are missing in a compiler pass and automatically disable the relevant services

**Comment by gquemener** [comment]
Oh yes, indeed. We could disable all services that depends on other symfony services that are not available.

**Comment by gquemener** [comment]
Here are the rules I've found so far that could be implemented inside a compiler pass:
- Remove `knp_rad.flash.message_renderer` if service `translator` is not registered
- Remove `knp_rad.twig.flash_extension` if service `session` is not registered (is that possible?)
- Remove `knp_rad.form.manager` if service `request` is not registered
- Remove `knp_rad.form.type_creator` if service `form.factory` or `form.registry` is not registered
- Remove `knp_rad.form.default_creator` if service `form.factory` is not registered
- Remove `knp_rad.twig.link_attributes_extension` if service `form.csrf_provider` is not registered
- Remove `knp_rad.csrf.listener` if service `form.csrf_provider` is not registered
- Remove `knp_rad.mailer.message_factory` if service `mailer` or `twig` is not registered
- Remove `knp_rad.orm.user_listener` if service `security.encoder_factory` is not registered
- Remove `knp_rad.routing.loader` if service `file_locator` is not registered
- Remove `knp_rad.view.listener` if service `templating` or `twig` or `controller_name_converter` is not registered
- Remove `knp_rad.view.path_deducer` if service `templating.name_parser` is not registered

Furthermore, it needs some more investigation to check if thoses services are somehow dependances of other services (that should then be also removed, etc.)!

Finally, I was thinking maybe it could be a nice idea to log warning about the fact that the service has been deactivated automatically and should be configured to be deactivated (or that user would need to install some 3rd party lib to enable this service).

What do you think @docteurklein @Herzult @everzet @lsmith77 ?

**Comment by lsmith77** [comment]
maybe there could be a command for this?

**Comment by lsmith77** [comment]
potentially also a profiler tab with status information about disabled features

**Comment by docteurklein** [comment]
yes, we should remove the whole service stack that depends on unexistant service. Removing `knp_rad.view.path_deducer` will make fail the AssistantController for example.

**Comment by docteurklein** [comment]
@lsmith77 @gquemener could we take advantage of http://symfony.com/doc/current/cookbook/bundles/prepend_extension.html to detect FrameworkBundle config `form: enabled` for example ?

**Comment by docteurklein** [comment]
/me is currently giving a try to prepend configurations.

**Comment by gquemener** [comment]
Woo, never heard about this feature before! Sounds like what we are trying to achieve here!

**Comment by gquemener** [comment]
As it is prepended configuration, I believe that if user explicitly defines `listener.orm_user: true` and the security services aren't available, then it would not be overwritten, right?

**Comment by docteurklein** [comment]
i'm checking. EDIT: works as expected: if you force the value to true in config, autodetection will be overwritten.

**Comment by docteurklein** [comment]
commiting right now for you to see: @lsmith77  @gquemener .
PS: specs didn't detect any change Oo. I'll have to write specs for that.

**Comment by docteurklein** [comment]
#104

**Comment by lsmith77** [comment]
@docteurklein i wouldnt use prepend extension for this. you dont really care about specific 3rd party bundles but the availability of certain services.

**Comment by docteurklein** [comment]
I'm just encountering problems, with order of removal, since some compiler passses seems to already have a reference on some (later removed) services. Trying to use TPYE_BEFORE_(REMOVING|OPTIMIZE) without success.

**Comment by docteurklein** [comment]
nevermind.
