### ISSUE TITLE
incorrect handling of missing "extends" templates

### ISSUE THREAD

**Issue by lsmith77** [KnpLabs/KnpRadBundle#96]
If an extends template is missing, it will trigger the missing view handling, which then suggests to create the action template again instead of realizing that its not the action template that is missing, but one of the extends, ie. parent, templates that is missing.

**Comment by docteurklein** [comment]
yes, we already noticed this problem. I think it's coming from the not explicit exception thrown by twig. It's hard to know why the template rendering fails.

**Comment by lsmith77** [comment]
I think we should just check in the missing view handler if the template exits or not .. and if it does .. then not present the form to create it .. but instead allow the normal exception to be thrown.

**Comment by docteurklein** [comment]
for the moment, we use "templating" service and call `->exists()`, which itself asks twig environment to `load` and check if it throws exception or not. 

https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/TwigEngine.php#L80
https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/TwigEngine.php#L122

So no way to know the previous exception and deduce if it's either a twig syntax error / extends / or inexistent file

But maybe you're right, just testing if the local file exists based on it's logical name could work.

**Comment by docteurklein** [comment]
what you could do too is call the inner environment  `return $this->templating->getEnvironment()->loadTemplate($name);` and get the exception.

**Comment by lsmith77** [comment]
aehm .. i am a bit confused in regards to the branches .. this didnt go into 2.3 but only develop .. but it appears develop isnt 2.3 compatible ..?

**Comment by docteurklein** [comment]
develop is 2.3 compatible. Starting from now, we merge develop into 2.3 as soon as it's stable.

So yes, once everything's ok in develop, we merge it into 2.3.

Is that ok for you ? If you have another way to handle the flow, I would be happy to hear it :)

**Comment by lsmith77** [comment]
ok .. i was just irritated that develop does not rebase cleanly on 2.3. that being said .. maybe its better to remove the 2.3 branch for now so that people do not use it instead of develop?

**Comment by docteurklein** [comment]
yes, indeed. I'm not sure about the best way of doing that 2.2 / 2.3 separation cleanly. I can delete 2.3 for the moment.
