### ISSUE TITLE
[MissingViewHandler] it should not override an existing file, never.

### ISSUE THREAD

**Issue by docteurklein** [KnpLabs/KnpRadBundle#97]

**Comment by gquemener** [comment]
i'm on it

**Comment by docteurklein** [comment]
:+1:  !

**Comment by gquemener** [comment]
Come ooooon, give me right to push on this repo!

**Comment by docteurklein** [comment]
héhé, no, fork it.

**Comment by docteurklein** [comment]
![gildas](http://i2.kym-cdn.com/entries/icons/original/000/000/185/nickcage.jpeg)

**Comment by PedroTroller** [comment]
@gquemener YEAH of course, it is allowed for all the KnpLabs team.......  Oh wait, nevermind.

**Comment by gquemener** [comment]
Pfff

**Comment by PedroTroller** [comment]
![tumblr_mao2jri9gi1qii6tmo1_500](https://f.cloud.github.com/assets/1766827/591585/36104fe4-ca04-11e2-86d9-dc60e45e8c5b.gif)

**Comment by docteurklein** [comment]
sorry I don't have sudo right.

**Comment by PedroTroller** [comment]
![tumblr_mm5vy9izp31r5xzspo1_500](https://f.cloud.github.com/assets/1766827/591593/8da909c6-ca04-11e2-952d-2e97057985fb.gif)
